channels:
  - conda-forge
dependencies:
  - python=3.9.13                       # https://pyreadiness.org/3.9/ 
  - pip=22.2.2                          # https://pip.pypa.io/en/stable/news/
  - nodejs=18.11.0                      # https://anaconda.org/conda-forge/nodejs
  - pip:
      - robotframework-browser==14.1.0  # https://github.com/MarketSquare/robotframework-browser/releases
      - rpaframework==17.7.0            # https://rpaframework.org/releasenotes.html
rccPostInstall:
  - rfbrowser init
